version: '3'

services:

  my_app:

    build:
      context: C:\Users\Matt\Documents\Ynov\B3\DevOps\Scripts\wik-dps-tp02-correction-rust\
      dockerfile: single-stage.dockerfile

    ports:
      - '8080'

    deploy:
      replicas: 4

    restart: always

    environment:
      - PORT=8080

    networks:
      - front-network

  proxy:

    image: nginx:latest

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    
    ports:
      - 8081:80

    depends_on: 
      - my_app

    networks:
      - front-network
  
networks:
  front-network:
    driver: bridge
